# Generated by Django 4.1.4 on 2023-09-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porfolio',
            new_name='portfolio',
        ),
    ]
